backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

local_backend: true # Enable for local development

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  # Company Information
  - name: "company"
    label: "Company Information"
    files:
      - label: "Company Details"
        name: "company-info"
        file: "content/company.json"
        fields:
          - { label: "Company Name", name: "name", widget: "string", default: "JBS MECHANICAL & ENGINEERING PTE LTD" }
          - { label: "Vision", name: "vision", widget: "markdown" }
          - { label: "Mission", name: "mission", widget: "markdown" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Company Logo", name: "logo", widget: "image", required: false }
      
      - label: "About Page Content"
        name: "about-content"
        file: "content/about.json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Company Story", name: "story", widget: "markdown" }
          - { label: "Expertise Highlights", name: "expertise", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" }
            ]}

  # Services Management
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Service Name", name: "title", widget: "string" }
      - { label: "Service Icon", name: "icon", widget: "string", hint: "Font Awesome icon class (e.g., fas fa-wrench)" }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Detailed Description", name: "detailed_description", widget: "markdown" }
      - { label: "Service Image", name: "image", widget: "image", required: false }
      - { label: "Features", name: "features", widget: "list", required: false }
      - { label: "Client Examples", name: "clients", widget: "list", required: false }
      - { label: "Display Order", name: "order", widget: "number", default: 1 }

  # Projects Management
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Project Name", name: "title", widget: "string" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Main Contractor", name: "main_contractor", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Project Duration", name: "duration", widget: "string", required: false }
      - { label: "Project Category", name: "category", widget: "select", 
          options: ["Daily Maintenance", "Annual SDM", "Fabrication", "Installation", "Inspection", "Construction"] }
      - { label: "Project Description", name: "description", widget: "markdown" }
      - { label: "Job Scope", name: "job_scope", widget: "list" }
      - { label: "Manpower Supplied", name: "manpower", widget: "list" }
      - { label: "Project Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" }, required: false }
      - { label: "Featured Project", name: "featured", widget: "boolean", default: false }
      - { label: "Status", name: "status", widget: "select", options: ["Completed", "Ongoing", "Upcoming"], default: "Completed" }

  # Manpower Categories
  - name: "manpower"
    label: "Manpower"
    folder: "content/manpower"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Position Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", 
          options: ["Welders", "Fitters", "Supervisors", "Safety Personnel", "Specialized Trades", "General Workers"] }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Key Skills", name: "skills", widget: "list", required: false }
      - { label: "Experience Level", name: "experience", widget: "string" }
      - { label: "Certifications", name: "certifications", widget: "list", required: false }
      - { label: "Position Image", name: "image", widget: "image", required: false }
      - { label: "Display Order", name: "order", widget: "number", default: 1 }

  # Certifications & Achievements
  - name: "certifications"
    label: "Certifications"
    folder: "content/certifications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Certification Name", name: "title", widget: "string" }
      - { label: "Issuing Authority", name: "authority", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Certificate Image", name: "image", widget: "image", required: false }
      - { label: "Valid Until", name: "validity", widget: "string", required: false }
      - { label: "Certificate Category", name: "category", widget: "select", 
          options: ["Safety", "Quality", "Technical", "Environmental"] }

  # Timeline/Road to Success
  - name: "timeline"
    label: "Company Timeline"
    files:
      - label: "Road to Success"
        name: "timeline"
        file: "content/timeline.json"
        fields:
          - label: "Timeline Events"
            name: "events"
            widget: "list"
            fields:
              - { label: "Year", name: "year", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Milestone", name: "milestone", widget: "boolean", default: false }

  # Contact Information
  - name: "contact"
    label: "Contact Information"
    files:
      - label: "Contact Details"
        name: "contact"
        file: "content/contact.json"
        fields:
          - { label: "Office Hours", name: "hours", widget: "string" }
          - { label: "Emergency Contact", name: "emergency", widget: "string", required: false }
          - { label: "Fax", name: "fax", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          - { label: "Google Maps Embed", name: "map_embed", widget: "text", required: false }
          - label: "FAQ Section"
            name: "faq"
            widget: "list"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "markdown" }

  # Website Settings
  - name: "settings"
    label: "Website Settings"
    files:
      - label: "SEO & Meta"
        name: "seo"
        file: "content/seo.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Keywords", name: "keywords", widget: "list" }
          - { label: "Author", name: "author", widget: "string" }
      
      - label: "Homepage Content"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "CTA Button Text", name: "cta_text", widget: "string" }
          - { label: "Featured Services Count", name: "featured_services", widget: "number", default: 6 }
          - { label: "Featured Projects Count", name: "featured_projects", widget: "number", default: 6 }

# Site URL (update this with your actual domain)
site_url: https://your-domain.com
display_url: https://your-domain.com

# Editorial workflow (optional)
# publish_mode: editorial_workflow 